### ISSUE TITLE
NodeGraph visualization support

### ISSUE THREAD

**Issue by trochumski** [marcusolsson/grafana-json-datasource#104]
I have attempted to use this data source with "NodeGraph" visualization
The documentation at https://arrow.wd1.myworkdayjobs.com/pl-PL/AC/job/PL-Gdansk-Poland-Aleja-Grunwaldzka/Senior-Linux---Embedded-Engineer_R184175
states that:

> Data source needs to return two data frames, one for nodes and one for edges and you also have to set frame.meta.preferredVisualisationType = 'nodeGraph' on both data frames.

I have created two queries to supply those two "data frames".

NodeGraph didn't work though.
Anything that is missing ?

```
# Query A
$.nodes[*].id
$.nodes[*].title

# Query B
$.edges[*].id
$.edges[*].source
$.edges[*].target
```

With data:
```
{
  "nodes": [  
    {
      "id": "n0",
      "title": "Node one"
    },
    {
      "id": "n1",
      "title": "Node two"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "source": "n0",
      "target": "n1"
    }
  ]
}         
```

**Comment by marcusolsson** [comment]
This is indeed a limitation in the node graph. Since the panel requires preferredVisualisationType to be set, every data source needs to provide explicit support for the node graph.

I've opened a [feature request](https://github.com/grafana/grafana/issues/33567) for this. Depending on how tricky it'll be to solve, I'll consider adding a temporary fix to set preferredVisualisationType from the query editor.

**Comment by marcusolsson** [comment]
Closing this as this is not an issue with the plugin, but a limitation in the node graph panel.

**Comment by Manoj3mvsr** [comment]
> This is indeed a limitation in the node graph. Since the panel requires preferredVisualisationType to be set, every data source needs to provide explicit support for the node graph.
> 
> I've opened a [feature request](https://github.com/grafana/grafana/issues/33567) for this. Depending on how tricky it'll be to solve, I'll consider adding a temporary fix to set preferredVisualisationType from the query editor.


@marcusolsson was the temporary fix of setting preferredVisualisationType from the query editor implemented?. I am trying to connect json api data source to node graph and having an issue.
