### ISSUE TITLE
Use `JSON.strignify` to convert objects to string instead of `toString`

### ISSUE THREAD

**Issue by Totalus** [marcusolsson/grafana-json-datasource#110]
### The Problem

It is currently not possible to extract nested objects from the query because the `.toString()` function applied on Javascript objects when parsing values returns `"[object Object]"` which is useless. Using `JSON.stringify()` instead for objects will give us the JSON as string, which can be used and displayed as JSON in grafana.

### Suggested Solution

This line:

https://github.com/marcusolsson/grafana-json-datasource/blob/37b14b5abf420cb93798c98e0eda93ef530fb4d9/src/parseValues.ts#L31

Would become something like:

```js
    return values.every((_) => typeof _ === 'string') ? values : values.map((_) => {
          if(_ === null) return _;
          else if(typeof(_) === 'object') return JSON.strignify(_); // Provides a proper output string for objects
          else return _.toString();
});
```

Note that `typeof(_) === 'object'` will match Objects and Arrays. If you want to avoid matching arrays, use `typeof(_) === 'object' && !Array.isArray(_)`. It mainly depends on which output you prefer for arrays:

```js

console.log([1,2,3].toString());             // Output: '1,2,3'
console.log(JSON.strignify([1,2,3]));        // Output: '[1,2,3]'
```

**Comment by marcusolsson** [comment]
Like you say, the current solution is pretty much useless so this is definitely an improvement. I think we could probably use JSON.stringify for both objects and arrays tbh.

Would you be up for submitting the pull request for this?

**Comment by Totalus** [comment]
Can you publish a new release from it ?

**Comment by marcusolsson** [comment]
Included in v.1.2.0
