### ISSUE TITLE
Data processing

### ISSUE THREAD

**Issue by marcusolsson** [marcusolsson/grafana-json-datasource#114]
Several users have reached out to me regarding support for data processing. So far I've focused on making it really easy to query data, leaving any processing of data to Grafana itself. 

However, data processing is currently limited in Grafana. Rather than to wait for more processing capabilities, let's discuss whether there's a way we can add it to the plugin.

The way I see it is that we could add custom processing to the results of a JSONPath expression. For simple array functions, this could be just a drop-down with `count`, `length`, `sum` etc. More advanced processing would likely result in a rather complex UI.

Another alternative is to use a query language that supports data processing, such as [JSONata](https://jsonata.org/).

**Comment by albertored** [comment]
JSONata seems a very good solution!

**Comment by valdemarpavesi** [comment]
perfect!


`
package main

import (
	"encoding/json"
	"fmt"
	"log"

	jsonata "github.com/blues/jsonata-go"
)

const jsonString = `
    {
        "orders": [
            {"price": 10, "quantity": 3},
            {"price": 0.5, "quantity": 10},
            {"price": 100, "quantity": 1}
        ]
    }
`

func main() {

	var data interface{}

	// Decode JSON.
	err := json.Unmarshal([]byte(jsonString), &data)
	if err != nil {
		log.Fatal(err)
	}

	// Create expression.
	e := jsonata.MustCompile("$sum(orders.(price*quantity))")

	// Evaluate.
	res, err := e.Eval(data)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(res)
	// Output: 135
}

`

`
./jsonata 
135
`

**Comment by jonnor** [comment]
JSONata now seems to be supported (based on the documentation), so maybe this can be closed?

**Comment by marcusolsson** [comment]
Good catch!
