### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by stefan-g** [marcusolsson/grafana-json-datasource#156]
I updated the grafana-json-datasource plugin to the latest version and now i got the error "Cannot read property 'filter' of undefined" when the defined variables in grafana are loaded. I got the same error when i try to define a new variable. Any hint what's wrong?

**Comment by marcusolsson** [comment]
Thank you for reporting 🙏  I'm able to reproduce the issue, and will be taking a look at it during the day.
