### ISSUE TITLE
Latest update seems to have broken query parameters

### ISSUE THREAD

**Issue by covertbert** [marcusolsson/grafana-json-datasource#16]
Since the last update, my API requests all seem to be returning the default data for an endpoint and ignoring any query parameters

**Comment by marcusolsson** [comment]
Thanks for letting me know. For your information, the data source was still sending the query parameters, but was flipped, i.e. `filter=true` become `true=filter`. I've published a fix in [v0.6.4](https://grafana.com/grafana/plugins/marcusolsson-json-datasource/changelog?version=0.6.4). Let me know if you're still experiencing any issues!

**Comment by covertbert** [comment]
Works perfectly again, cheers mate!
