### ISSUE TITLE
JSON API install fails

### ISSUE THREAD

**Issue by paulmcclellan** [marcusolsson/grafana-json-datasource#167]
I must be doing something wrong?  In the Grafana docker shell I entered "grafana-cli plugins install marcusolsson-json-datasource".  It was successful.  But when I try to add JSON API as a data source in Grafana GUI, I get this error:

An unexpected error happened
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    in Unknown
    in div
    in t
    in form
    in div
    in div
    in t
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in x
    in ConnectWithCleanUp(Connect(t))
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l

Help!

TIA!

**Comment by marcusolsson** [comment]
Hi, and thanks for reporting! 

What version of Grafana and the plugin are you running?

**Comment by paulmcclellan** [comment]
Looks like user error.  Closing.
