### ISSUE TITLE
Doesn't parse multiple params with the same key

### ISSUE THREAD

**Issue by ideasman69** [marcusolsson/grafana-json-datasource#169]
Hi there,

The API we're hitting via the JSON API allows/requires multiple parameters with the same key. To request a single metric from the api, the URL is formed like this:
`https://host/api/metrics?id=D6B1359061A2EAEDDC287872174700FDB&id_lookup=by_device_id&metricFilter=QOS_MEMORY_PHYSICAL_PERC&metric_type_lookup=by_metric_name&period=latest&showSamples=true`

To obtain _two_ metrics from the same host _(note the dual metricFilter params)_:
`https://host/api/metrics?id=D6B1359061A2EAEDDC287872174700FDB&id_lookup=by_device_id&metricFilter=QOS_MEMORY_PHYSICAL_PERC&metricFilter=QOS_MEMORY_PHYSICAL&metric_type_lookup=by_metric_name&period=latest&showSamples=true`

However, when configuring the metricFilter parms in the dashboard editor:
![image](https://user-images.githubusercontent.com/19260137/132620850-2a1c3dbd-003b-412e-959c-dc7d4a6ee6e5.png)

Only the second one is passed to the API:
![image](https://user-images.githubusercontent.com/19260137/132620920-7f8fc59d-ebcc-4b94-aef2-ef8b124576af.png)

Just wondering if it's a bug or if there's a workaround I'm not aware of?

Thanks!

**Comment by marcusolsson** [comment]
The plugin currently stores the params as a dictionary. If you set the same param multiple time, only the last value will be kept. I don't think there's any harm in changing it, but I don't there's a workaround for it, unfortunately.

**Comment by rejohnst** [comment]
FWIW, I'm also hitting this issue trying to construct a dashboard panel that queries the Prometheus Alertmanager API.  That API supports specifying multiple "filter" parameters when querying alerts to allow for filtering on multiple labels values in the alert payload. 

I think this API pattern is not uncommon and so it would be nice to come up with a solution.  I would be willing to help develop a fix for this.

**Comment by marcusolsson** [comment]
I think it should be fairly safe to update the behavior. I'd be happy to accept a PR for this 🙏

**Comment by marcusolsson** [comment]
Fix available in v1.3.1.
