### ISSUE TITLE
%2F is always replaced with backslash which may brakes CouchDB

### ISSUE THREAD

**Issue by wrazik** [marcusolsson/grafana-json-datasource#186]
Hi!
I'm trying to set up CouchDB data source with JSON API. I have a document in which "_id" contains backslashes, for example:
```
some/id
```
Full path to such object is:
```
localhost:5984/db_name/some%2Fid
```
Because of nature of CouchDB, below address is incorrect (it means "document with _id=some, field named 'id'")
```
localhost:5984/db_name/some/id
```
JSON API always replaces %2F with backslashes, so user can't setup address correctly.

There is a workaround for this - you have to encode `%` as html code `%25`:
```
localhost:5984/db_name/some%252Fid
```

**Comment by marcusolsson** [comment]
Closing as duplicate.
