### ISSUE TITLE
fields have different length

### ISSUE THREAD

**Issue by jinxiao** [marcusolsson/grafana-json-datasource#20]
when i tried use chinese character in json fields, it always showed "fields have different length"
so my question is , is there any limitations when i use this plugin ? especially the length of fields
thanks

**Comment by marcusolsson** [comment]
Could you provide a JSON payload, and the corresponding queries that demonstrate the behavior so I can debug it?

**Comment by jinxiao** [comment]
```
{
	"items": [{
		"product_name": "全场通用100优惠券",
		"sku_code": "KUI90909023",
		"sku_stock": 0
	}, {
		"product_name": "【3色可选】郎朗推荐的TheONE智能电子琴Light，0基础5分钟也能上手，3天学会弹钢琴，已教会25万人弹琴",
		"sku_code": "FZH2018082121",
		"sku_stock": 136
	}, {
		"product_name": "加绒高领打底衫女秋冬长袖t恤内搭紧身上衣纯色百搭加厚保暖小衫",
		"sku_code": "FHP201712071058",
		"sku_stock": 4
	}]
}

this is my json payload , i tried to query $.items[*].product_name , $.items[*].sku_code and $.items[*].sku_stock

at the beginning , i tried to query these items, it showed fields have different error, however , i changed the order , put $.items[*].sku_stock to the first , it turned out to be ok. thanks

**Comment by marcusolsson** [comment]
I tried the data and query you listed, and looks like it's working for me. It sounds like you got it working though, so I'm closing this issue for now. Feel free to reopen if you encounter it again.

<img width="734" alt="Screen Shot 2020-12-03 at 16 14 01" src="https://user-images.githubusercontent.com/8396880/101047988-919df180-3582-11eb-9d2f-8c47af39d0dd.png">
