### ISSUE TITLE
Certain strings incorrectly identified as dates

### ISSUE THREAD

**Issue by markspolakovs** [marcusolsson/grafana-json-datasource#202]
It looks like the type auto-detection can incorrectly detect certain strings as dates. For example, `"foo bar 1.1"` is identified as 2001-01-01 - any string in the format `aaa aa x.x` where `a` is a letter and `x` is a number will be identified as 2001-x-x.

Here's the panel JSON:

```json
    {
      "datasource": "JSON API",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": "auto",
            "displayMode": "auto"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "showHeader": true
      },
      "pluginVersion": "8.2.3",
      "targets": [
        {
          "cacheDurationSeconds": 300,
          "fields": [
            {
              "jsonPath": "[\"aaa aa 1.1\"]",
              "language": "jsonata"
            }
          ],
          "method": "GET",
          "queryParams": "",
          "refId": "A",
          "urlPath": "/"
        }
      ],
      "title": "Panel Title",
      "type": "table"
    }
```

**Comment by marcusolsson** [comment]
Thanks for reporting this! I'm indeed able to reproduce this. It seem that dayjs recognizes the string as a valid date object:

https://github.com/marcusolsson/grafana-json-datasource/blob/779ba3d3bedb160efd0cb15c1bc346d78af58864/src/detectFieldType.ts#L14-L16

[After some digging](https://github.com/iamkun/dayjs/issues/320), `isValid()` apparently doesn't return whether the date is valid, but whether it was parsed correctly.

Think we should instead parse the date as ISO8601. If you have a different time format, then you can always set the type explicitly.
