### ISSUE TITLE
Passing a '/' into Path

### ISSUE THREAD

**Issue by MathieuEtchepare** [marcusolsson/grafana-json-datasource#215]
Hello,

I'm using your plugin to query my rabbitMQ cluster's API and as a parameter I must pass a '/'
Using urlencode, / = %2F
The query gives a path like this: /queues/%2F/name_of_queue

But when going through the plugin, it seems to be decoded as /queues///name_of_queue which doesn't work.

Is there a way to work this around?

Thank you

**Comment by jonnor** [comment]
This seems related to / possibly a duplicate of #59

**Comment by marcusolsson** [comment]
Thanks @jonnor for spotting 🙏 I'm closing this as a duplicate. Please continue the discussion in #59.
