### ISSUE TITLE
Template variable chaining is not working

### ISSUE THREAD

**Issue by oplehto** [marcusolsson/grafana-json-datasource#23]
I'm trying to chain template variables and it seems that the variable expansion is not working in the "Custom query parameters" field in template variables. When I set: 
```
search=$filter
```
The query becomes: 
```
/?search=%24filter
```
The same happens with the double-bracket notation. 

In the query editor this is working and only seems to affect the template variable editor.

**Comment by marcusolsson** [comment]
Thanks for reporting this! Fixed in the last PR.
