### ISSUE TITLE
Post enhancement

### ISSUE THREAD

**Issue by abenbouz** [marcusolsson/grafana-json-datasource#26]
hello Marcus ,

are you thinking of integrating Post request to the plugin via a button 

Thanks

**Comment by marcusolsson** [comment]
We could add a drop-down to set the HTTP method. I'm curious though: wouldn't that create a new resource on every dashboard refresh? Is that something you'd want?

**Comment by abenbouz** [comment]
hello Marcus ,
in my model i need to have the post or delete method on demand and not every refresh ( this is why i'm speaking about button )
in fact it's not like a GET that will monitor events , the Post or delete should apply some command on backend based on a payload 

Regards

**Comment by marcusolsson** [comment]
I see! The goal of this plugin is to read and visualize data from a JSON endpoint. I think what you're describing might be out of scope for this plugin. 

Have you considered using the [Button Panel](https://grafana.com/grafana/plugins/cloudspout-button-panel) for this?

**Comment by abenbouz** [comment]
hello Marcus ,
yeah you are right i do undestand that 
yes i tried Button Panel but it have some problems like having credentials not crypted !
thanks a lot for your actions

**Comment by abenbouz** [comment]
works as disigned
