### ISSUE TITLE
Minified React error #130

### ISSUE THREAD

**Issue by rickeymickey** [marcusolsson/grafana-json-datasource#27]
I installed this plugin on a Debian server and I encountered an issue when I tried to add a JSON API data source. "Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. " When I checked the URL, it showed that "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined." Is this a compatibility issue?

**Comment by stv0g** [comment]
I can reproduce the issue

**Comment by seanrclayton** [comment]
+1 on this. Do old versions work?

**Comment by marcusolsson** [comment]
Thanks for reporting this! Would you mind sharing your Grafana version? 

In my experience, this usually happens when you're using an unsupported Grafana version. From 0.7.0 of this plugin, the minimum required Grafana version is 7.3.0. Try installing a previous version.

**Comment by stv0g** [comment]
Hi @marcusolsson ,

I am using Grafana v7.1.5 (9893b8c53d)

**Comment by stv0g** [comment]
Does the Grafana Plugin API provide some metadata about plugin compatabilty?

**Comment by marcusolsson** [comment]
The required Grafana version is specified by `grafanaDependency` in the [plugin.json](https://github.com/marcusolsson/grafana-json-datasource/blob/b7cefd76e68d6337eb43a5d044347b92ec113331/src/plugin.json#L44) file.

The `grafana-cli` tool should only install plugins for Grafana installations that satisfy that semver requirement. If you install the plugin manually though, there's no check currently.

I've [created an issue](https://github.com/grafana/grafana/issues/29660) on the grafana repository to make this clearer.

**Comment by stv0g** [comment]
Hi @marcusolsson,

thanks for clarifying. I guess we can close the issue then.

Cheers,
Steffen
