### ISSUE TITLE
Grafana Explore gets stuck when adding a second query

### ISSUE THREAD

**Issue by adyanth** [marcusolsson/grafana-json-datasource#31]
I will add a video to show what I mean. The 1st query works just fine. But after that, I cannot add another query at all. Whatever I click on the grafana explore pane does nothing.

https://user-images.githubusercontent.com/33192449/103198981-b9793e80-490f-11eb-8ebf-2dfc6ea46ad5.mp4

**Comment by marcusolsson** [comment]
Thanks for reporting this. I can reproduce this. Like you say, this seems to only be an issue in Explore. The editor seems to work for dashboards and for query variables.

**Comment by adyanth** [comment]
One more issue I see in the dashboard section, when I add a new query, it copies the existing data, and if I modify one, it is modifying both, so cannot add two separate queries at all.  A typical bug with shallow vs deep copy? : )


https://user-images.githubusercontent.com/33192449/103358859-a36ca900-4adc-11eb-8172-f712a7c4a5c1.mp4

**Comment by marcusolsson** [comment]
Good find! Huge thanks for reporting all these issues. I'll do my best to get this sorted out as soon as possible 🙏

**Comment by adyanth** [comment]
Sure, my pleasure!

**Comment by marcusolsson** [comment]
> One more issue I see in the dashboard section, when I add a new query, it copies the existing data

I can't seem to reproduce this on Safari or Chrome. What version of the plugin are you running?

**Comment by adyanth** [comment]
I am running it in a docker container with the below env var:
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,marcusolsson-json-datasource

Which is pulling Version 0.7.1, and I am running Edge (Chromium based) v87 and Chrome v87
