### ISSUE TITLE
Support for time series data

### ISSUE THREAD

**Issue by adyanth** [marcusolsson/grafana-json-datasource#32]
Does this have support for generating graphs from the JSON data which is updated in real time? Or do I need prometheus for it and then use it in grafana?

**Comment by marcusolsson** [comment]
To graph data in Grafana, the query result needs to contain a time field and a number field. The plugin detects time fields by checking if it's a valid ISO 8601 string, or if it looks like a UNIX epoch.

Let me know if you have trouble graphing data with this plugin!

**Comment by adyanth** [comment]
Here is the sample data from the API below, and my JsonPath query is `$[?(@.SensorName == "Physical Memory Used")].SensorValue`. (I tried the whole object too, `$[?(@.SensorName == "Physical Memory Used")]`)

The SensorUpdateTime is indeed in Unix epoch time.
This is what I get on Grafana:
![image](https://user-images.githubusercontent.com/33192449/103327645-691eef80-4a7b-11eb-9f81-933a32fa7fe7.png)
After switching to table view:
![image](https://user-images.githubusercontent.com/33192449/103327659-79cf6580-4a7b-11eb-8162-a9746d0d353c.png)
With the full object:
![image](https://user-images.githubusercontent.com/33192449/103327681-923f8000-4a7b-11eb-9753-24885055b9b5.png)

Let me know if I am doing something wrong here and thanks for looking into this!

```json
[
  {
    "SensorApp": "HWiNFO",
    "SensorClass": "System: MSI MS-7C92",
    "SensorName": "Virtual Memory Commited",
    "SensorValue": "13857",
    "SensorUnit": "MB",
    "SensorUpdateTime": 1609297850
  },
  {
    "SensorApp": "HWiNFO",
    "SensorClass": "System: MSI MS-7C92",
    "SensorName": "Virtual Memory Available",
    "SensorValue": "27028",
    "SensorUnit": "MB",
    "SensorUpdateTime": 1609297850
  },
  {
    "SensorApp": "HWiNFO",
    "SensorClass": "System: MSI MS-7C92",
    "SensorName": "Virtual Memory Load",
    "SensorValue": "33.8",
    "SensorUnit": "%",
    "SensorUpdateTime": 1609297850
  },
  {
    "SensorApp": "HWiNFO",
    "SensorClass": "System: MSI MS-7C92",
    "SensorName": "Physical Memory Used",
    "SensorValue": "10133",
    "SensorUnit": "MB",
    "SensorUpdateTime": 1609297850
  }
]
```

**Comment by marcusolsson** [comment]
As I mentioned earlier

> the query result needs to contain a time field and a number field

In your case, you seem to have neither :)

- SensorValue is a string. The plugin would need to support parsing strings as numbers which it currently doesn't. If this is important to you, please create a feature request.
- In your screenshot, you don't seem to extract the SensorUpdateTime. You'd need to add another JSON Path query referencing the property you'd like to use for the timestamp.

**Comment by adyanth** [comment]
Okay, I tried that. This recognizes the date format, but does not plot anything. When I said that JSON updates in real time, I meant that the JSON will only be for the current instance. It won't have data for the previous time instances.

So, I don't think this is possible with this data source, since I believe it is expecting the complete data to be sent over, rather than just the current data. My JSON source is sending data *only* for the current time instance, the next time you request, it would respond with new data.

![image](https://user-images.githubusercontent.com/33192449/103358600-f7c35900-4adb-11eb-9d53-284f0cdc2a76.png)

**Comment by marcusolsson** [comment]
Oh I see. Yeah, this plugin doesn't keep state at all. The JSON response need to contain the entire time series. If you want to store historical data, then I agree that something like Prometheus would be a better option 💯

**Comment by adyanth** [comment]
Yeah, I already did that on a dashboard for the same data source with a custom JSON exporter ([Here](https://github.com/adyanth/hwinfo-exporter) and [here](https://github.com/adyanth/hwinfo-monitor)). That works good. 
I wanted to do it only in grafana because I was planning to run the whole thing on a raspberry pi which is already overloaded with this, and don't think can handle prometheus too : ) + I don't need more than like 60 samples at best, so keeping historical data does not help. I think I can roll a JSON -> JSON stateful adapter to save those samples if I plan to use this.

Thanks for looking into this, greatly appreciated! Happy holidays!
