### ISSUE TITLE
add json api datasource failed

### ISSUE THREAD

**Issue by chuan-T** [marcusolsson/grafana-json-datasource#35]
Hello,
I installed the plugin, but when I click add in the grafana configuration screen, I get an error
The error message is as follows

Error: Object prototype may only be an Object or null: undefined Evaluating https://grafana.automizely.org/public/plugins/marcusolsson-json-datasource/module.js Loading plugins/marcusolsson-json-datasource/module

https://user-images.githubusercontent.com/43464580/103627841-1c567f80-4f79-11eb-9ccc-ff38fbff67c1.mov

Thanks for your help

**Comment by marcusolsson** [comment]
Hi @chuan-T,

I see that you're using Grafana 6.3.5. This plugin requires Grafana 7.3.0 or later. Are you able to try the plugin on a later version of Grafana?

**Comment by chuan-T** [comment]
@marcusolsson  thanks,I also found this error, the new version does not have this problem
