### ISSUE TITLE
Issue with registration

### ISSUE THREAD

**Issue by ezerog** [marcusolsson/grafana-json-datasource#38]
![image](https://user-images.githubusercontent.com/49855356/104526167-1e899f80-5645-11eb-8933-357c078da013.png)

I got an issue like above when I tried registering this datasource to grafana.
I installed this well with same way to install other plugins. 😢

**Comment by marcusolsson** [comment]
Unfortunately it's not a very informative error, but usually this means that the plugin is using features/APIs from a more recent version of Grafana. You can find the minimum required Grafana version in the [`plugin.json`](https://github.com/marcusolsson/grafana-json-datasource/blob/7e195eed36a2d11bf4f011bd1a57be6adfba452e/src/plugin.json#L44).
