### ISSUE TITLE
Can I add a custom http parameter?

### ISSUE THREAD

**Issue by casieo** [marcusolsson/grafana-json-datasource#39]
I am getting some data back using this against sprinklr.  woot!  To get data back from their listening stream (actual verbatim comments), an http parameter is required.  For example:

`request.AddParameter(@"application/json", "{\n\t\"sinceTime\":" + epochFromInMilliseconds + ",\n\t\"untilTime\":" + epochNowInMilliseconds + ",\n\t\"details\": {\n\t\t\"widgetType\": \"STREAM\"\n\t},\n\t\"messageFormatOptions\": \"strip_html,strip_url\",\n\t\"filters\": [\n\t\t{\n\t\t\t\"dimension\": \"TOPIC\",\n\t\t\t\"filterValues\": [\n\t\t\t\t\"" + definedTopic.Id + "\"\n\t\t\t]\n\t\t},\n\t\t{\n\t\t\t\"dimension\": \"MEDIA_SOURCE\",\n\t\t\t\"filterValues\": [\n\t\t\t\t\"REDDIT\",\n\t\t\t\t\"TWITTER\",\n\t\t\t\t\"FACEBOOK\"\n\t\t\t]\n\t\t}\n\t],\n\t\"metric\": \"MENTIONS\",\n\t\"start\": 0,\n\t\"rows\": 150\n}", ParameterType.RequestBody);`

Does this support that as is?  Thanks!

**Comment by marcusolsson** [comment]
Depends on what you mean by "http parameter". The plugin supports custom query parameters, i.e. `?filter=100&page=1`, but based on your example it looks like you want to send a JSON body with your HTTP request? This is not supported unfortunately. If this is something you think would be a good addition to the plugin, please create a feature request explaining what you'd like to see.

**Comment by casieo** [comment]
great, created feature request (#40).
