### ISSUE TITLE
Column alias is gone?

### ISSUE THREAD

**Issue by tato69** [marcusolsson/grafana-json-datasource#42]
In the newest release (0.8.0) it seems like the alias field is not present anymore.
![image](https://user-images.githubusercontent.com/15939127/104926856-f2ea1a80-59a0-11eb-9f48-8314ffdcefa6.png)

The aliases i had in place are working correctly but i cannot create new ones.

Is it an intended change? 

Thank you in advance

**Comment by marcusolsson** [comment]
Yes. With recent versions of Grafana, this is now built into Grafana itself. You can either use the Organize fields transformation, or override the display name using field options. Please try it out and let me know if it works for you.

**Comment by tato69** [comment]
Hello @marcusolsson, you are indeed right! 
I was able to change the field name using an override!

Transformation doesn't seem to be an option tho
![image](https://user-images.githubusercontent.com/15939127/104930998-224f5600-59a6-11eb-8030-f815a4df2ac3.png)

Thank you very much for the lighting fast feedback and mostly for this awesome plugin :)

**Comment by marcusolsson** [comment]
Glad you got it to work! And thanks for the kind words!
