### ISSUE TITLE
Data query trigger by variable change, but the query not use the changed variable value

### ISSUE THREAD

**Issue by smarkm** [marcusolsson/grafana-json-datasource#44]
The panel title changed and as I check the query trigger by variable change, but the result seems not use the changed value

![image](https://user-images.githubusercontent.com/5517120/105825491-9dde8200-5ffa-11eb-9808-5cde249ffe1a.png)

**Comment by marcusolsson** [comment]
Thank you for reporting this! My gut feeling is that this is related to the cache. Does the error persist if you change the cache time to 0s?

**Comment by smarkm** [comment]
> Thank you for reporting this! My gut feeling is that this is related to the cache. Does the error persist if you change the cache time to 0s?

Thanks @marcusolsson , it's worked after the cache time change to 0s, if this a default design please close this issue

**Comment by marcusolsson** [comment]
Good question. You could argue that changing variables should invalidate the cache. My thoughts are that you probably use the cache to avoid hitting API quotas etc, so I'm inclined to keep the current behavior.

Do you think it would've helped you if this was added to the README instead?

**Comment by smarkm** [comment]
> Good question. You could argue that changing variables should invalidate the cache. My thoughts are that you probably use the cache to avoid hitting API quotas etc, so I'm inclined to keep the current behavior.
> 
> Do you think it would've helped you if this was added to the README instead?

Yes, it will help if added a description to the README, but I don't know much about the cache used here, the cache here is trying to resolve the API  data update rate not match the dashboard refresh interval?

**Comment by marcusolsson** [comment]
Yes. The reason behind the cache is to avoid being hit with rate limits while working on your queries. If you set it to 0s, it will refresh whenever the dashboard refreshes.

**Comment by smarkm** [comment]
> Yes. The reason behind the cache is to avoid being hit with rate limits while working on your queries. If you set it to 0s, it will refresh whenever the dashboard refreshes.

Got it, thank you @marcusolsson
