### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by naman7kr** [marcusolsson/grafana-json-datasource#46]
I am getting error "Cannot read property 'toString' of null" while reading 
[error.json](https://github.com/marcusolsson/grafana-json-datasource/files/5903466/error.txt) in version 0.8.0. Version 0.7.1 does not produce this error

**Comment by marcusolsson** [comment]
I can reproduce this and working on a fix. Thank you for reporting this! ❤️

**Comment by marcusolsson** [comment]
I've published 0.9.1 which should hopefully fix this issue. Heads-up though: 0.9.0 introduces a new query editor, so make sure you back up your dashboard before updating.

Let me know if the problem persists!
