### ISSUE TITLE
Version 0.9.1 failed to load on installation 

### ISSUE THREAD

**Issue by sudivate** [marcusolsson/grafana-json-datasource#47]
Installed v 0.9.1 on Grafana version 7.2.1.  The new plugin doesn't load and throws the below error.

![image](https://user-images.githubusercontent.com/28938855/106538604-59972a00-64b1-11eb-80f8-68d994ae3d9d.png)

**Comment by marcusolsson** [comment]
You'll see this error whenever you're trying to load a plugin that's using features from a more recent Grafana version. Since 0.7.0, the minimum Grafana version supported is 7.3. Could you try loading it using a more recent Grafana?
