### ISSUE TITLE
Issues with dashboard variables relying on JSON API datasource

### ISSUE THREAD

**Issue by victornoventa** [marcusolsson/grafana-json-datasource#48]
Prior to updating to the latest version, we had been able to use JSON API to fetch data and store it in a variable. Now we get the following error:

![Screen Shot 2021-02-02 at 18 53 38 (2)](https://user-images.githubusercontent.com/4095856/106668733-61c29880-6589-11eb-97ca-e33c5e4e5dca.png)

**Comment by marcusolsson** [comment]
Thanks for reporting this (and sorry about that)! I'll get a fix out today.

**Comment by marcusolsson** [comment]
Fixed in 0.9.2.

**Comment by victornoventa** [comment]
Thank you very much for your fast support! Really appreciate it! Everything is working fine now. 😀
