### ISSUE TITLE
when the value is blank "Cannot read property 'toString' of null"

### ISSUE THREAD

**Issue by misterbaldi** [marcusolsson/grafana-json-datasource#52]
The datasource where i do the query, reports me a tag back "NAME": null, - the table / datasource note - Cannot read property 'toString' of null
is there a workaround?

**Comment by marcusolsson** [comment]
Thanks for reporting this issue! Could you give me some more information where you're seeing this error? Can you provide a screenshot (with anonymized data)?

**Comment by misterbaldi** [comment]
hi yes 
![error1](https://user-images.githubusercontent.com/7579079/106753888-9176ac80-662c-11eb-8685-828b183c3d5f.PNG)
![error2](https://user-images.githubusercontent.com/7579079/106753894-920f4300-662c-11eb-9193-1c1385af8afb.png)
if u want a screenshot from the sourcejson also possible, but its same like the query inspector

**Comment by marcusolsson** [comment]
I think this might be the same issue as https://github.com/marcusolsson/grafana-json-datasource/issues/46, which has been fixed.

Could you try to update the plugin to the latest version?

**Comment by misterbaldi** [comment]
Hi,
thank u for your fast support, now its working!!
is it possible in the query field to do some regex functions? replace?

![image](https://user-images.githubusercontent.com/7579079/106758264-9ab64800-6631-11eb-8777-4240f0e87a9c.png)

**Comment by marcusolsson** [comment]
Great to hear! 

The query field is using https://github.com/JSONPath-Plus/JSONPath. Feel free to check out their documentation to see what's possible. There seems to be some regex support.
