### ISSUE TITLE
New params are missing in final query

### ISSUE THREAD

**Issue by debardev** [marcusolsson/grafana-json-datasource#58]
Hello, first of all, thank you very much for the new features / improvements. This is a great plugin that helps us a lot!

From Release Notes of v.0.9.0:

```
It introduces a new key value editor for query parameters and headers, as well as a Monaco-based editor for editing the request body with syntax highlighting.

This release deprecates the queryString property in the query model, in favor of the new params. The query string config should be backwards-compatible (and forward-compatible) with previous versions, but make sure to back up your dashboard before upgrading.
```

Query string was greatly parsed to params:
![image](https://user-images.githubusercontent.com/34651136/107754315-9836ab00-6d21-11eb-8928-aa2411ed9f56.png)

But all of them are missing in the final query:
![image](https://user-images.githubusercontent.com/34651136/107754525-e481eb00-6d21-11eb-8df5-47ce9796c146.png)

So I had to use the path configuration to pass query as workaround:
![image](https://user-images.githubusercontent.com/34651136/107754647-109d6c00-6d22-11eb-83b7-966aef14c765.png)

Thank you for any support!

**Comment by marcusolsson** [comment]
Hey, and thank you for using the plugin!

I tried to reproduce this, but it seems to be working for me:

<img width="609" alt="CleanShot 2021-02-12 at 11 25 30@2x" src="https://user-images.githubusercontent.com/8396880/107756819-0d57af80-6d25-11eb-84e6-21fa3f13f039.png">

What version of Grafana and the plugin are you currently running?

**Comment by debardev** [comment]
Grafana v7.3.6
Plugin v0.9.2

It seems to happen only when opening dashboard created for an older grafana-json-datasource (~0.7.0). Probably some backward compatibility issue. It works fine when I create a new dashboard with the latest plugin version.

**Comment by marcusolsson** [comment]
Hm. The plugin _should_ automatically migrate the old query model to the new format. You can inspect the query model in the panel JSON:

![CleanShot 2021-02-12 at 11 54 23@2x](https://user-images.githubusercontent.com/8396880/107759845-2c584080-6d29-11eb-94c0-dc930b099177.png)

The old format uses the "queryString" property:

```
  "targets": [
    {
      // ...
      "queryString": "foo=bar-${__from}"
    }
  ],
```

The new format uses a "params" property

```
  "targets": [
    {
      // ...
      "params": [
        [
          "foo",
          "bar-${__from}"
        ]
      ]
    }
  ],
```

When you open an old dashboard and save it, the plugin reads from the queryString property and saves it as params. The old property will still be there, but ignored.

I understand if you decide to just create the dashboards afresh, but if you want to dig deeper. I'd be curious to what went wrong here.
