### ISSUE TITLE
Unexpected token '<' Evaluating ...

### ISSUE THREAD

**Issue by alturismo** [marcusolsson/grafana-json-datasource#60]
Hi, as i would like to add some stats from a json into grafana i tried to load this plugin

grafana version is Open Source v7.3.7 (1e261642f4) running in a docker

when i try to add datasource it drops directly this error

Unexpected token '<' Evaluating http://192.168.1.97:3006/public/app/plugins/datasource/dist/module Loading app/plugins/datasource/dist/module
Data Source Error

![image](https://user-images.githubusercontent.com/8406490/107862793-8bb07080-6e4f-11eb-8d21-7f88bdc8167b.png)

from the dev console in browser
actions.ts:70 Failed to import plugin module SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at le (system.js:4)
    at system.js:4
    at system.js:4
    at S (system.js:4)
    at x (system.js:4)
    at system.js:4

also not possible to remove the failed entries anymore
![image](https://user-images.githubusercontent.com/8406490/107862809-b7cbf180-6e4f-11eb-9c1e-6b02596050e8.png)

way i installed, downloaded the zip, moved to the proper directory where the plugins are located, restarted server, datasource was available, but as soon i hit "add" ...

i also tried then to compile in the docker
installed yarn
but compiling is ... not very well documented howto use yarn, yarn build drops also a error

root@e654c4951362:/usr/share/grafana/public/app/plugins/datasource/grafana-json-datasource-main# yarn build
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'
root@e654c4951362:/usr/share/grafana/public/app/plugins/datasource/grafana-json-datasource-main# yarn package.json 
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
root@e654c4951362:/usr/share/grafana/public/app/plugins/datasource/grafana-json-datasource-main# yarn build package.json 
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'
root@e654c4951362:/usr/share/grafana/public/app/plugins/datasource/grafana-json-datasource-main# 

for any Tipps, thanks ahead

**Comment by marcusolsson** [comment]
Hm. This usually means that Grafana found a plugin that only has the source code, but is missing the compiled assets. Where did you download the ZIP from?

If you'd like to use the plugin, I recommend that you install it using grafana-cli:

```
grafana-cli plugins install marcusolsson-json-datasource
```

If you want to download a release from GitHub, make sure that you're downloading the release asset called `marcusolsson-json-datasource-0.9.2.zip`.

**Comment by alturismo** [comment]
thanks for the info, well, i did install it from your release section, but actually i did it again now and removed the source folder from the plugins section (tried to compile yarn) and looks it works now ... whyever ;)

thanks for pointing again, my fault

now i just have to figure how to use the respond

**Comment by marcusolsson** [comment]
No worries! If you run into any more trouble, let me know! If you have any questions on how to use the plugin, feel free to start a [Discussion](https://github.com/marcusolsson/grafana-json-datasource/discussions).

**Comment by vrej-abramian** [comment]
Hi @marcusolsson, could you please also help me with a similar issue?
* Grafana is deployed by `helm` `v7.3.6 (ea06633c34)`. 
  * I know the version is old but it is deployed from our local repository & totally enough for the scopes we are using it. Resolving the plugin issue without needing to upgrade the Grafana version would be much appreciated.
* The plugin is mentioned in the helm `.Values.plugins`
```yaml
plugins:
  - marcusolsson-json-datasource
```
* Here is the version checking from within the pod: `grafana-cli plugins ls : marcusolsson-json-datasource @ 1.3.4`
  * What is interesting is that I didn't find such a version in the [GitHub releases](https://github.com/grafana/grafana-json-datasource/releases)

It was working properly until today noticed the following error, nothing was changed/updated in Grafana (as much as I checked).
Both on attempting to create a new datasource and on opening the existing datasources of this kind we got the following:
```text
Unexpected token '<' Evaluating https://prod.grafana.<MY_DOMAIN>.net/public/@emotion/css Loading plugins/marcusolsson-json-datasource/module
Data Source Error
```
Accordingly, dashboards using `marcusolsson-json-datasource` datasource also not working as well.

What I have tried:
* Restarted the Grafana pod.
* Uninstalled the plugin by `grafana-cli` & redeployed the pod - the `/var/lib/grafana/plugins/marcusolsson-json-datasource` directory has been created but still getting the same error.

PS. Please let me know if any further info was needed. Thank you in advance.
