### ISSUE TITLE
Show decimal value 

### ISSUE THREAD

**Issue by smarkm** [marcusolsson/grafana-json-datasource#63]
The result decimal  auto transformed, I am not sure this transformed by this data source or grafana internal ?
![image](https://user-images.githubusercontent.com/5517120/108179446-96fde780-7140-11eb-86a3-7b2fc90d7e4c.png)

**Comment by marcusolsson** [comment]
Does it work if you set the number of Decimals in the field config?

**Comment by smarkm** [comment]
> Does it work if you set the number of Decimals in the field config?

It's worked, thank you for your tips @marcusolsson
