### ISSUE TITLE
Feature request: Can be input or select api base  on API category result

### ISSUE THREAD

**Issue by smarkm** [marcusolsson/grafana-json-datasource#64]
![image](https://user-images.githubusercontent.com/5517120/108330993-42726f00-7209-11eb-98d2-a7c1978ca25c.png)
![image](https://user-images.githubusercontent.com/5517120/108331326-a09f5200-7209-11eb-8bf0-9f50416a8183.png)
The API category result maybe looks like this:
```JSON
[
  {
    "api":"/api/resource/a",
    "files":[
      "$.data[*].name",
      "$.data[*].age"
      ]
  },
  {
    "api":"/api/resource/b",
    "files":[
      "$.data[*].name",
      "$.data[*].age"
      ]
  }
]
```

**Comment by marcusolsson** [comment]
Do you mean something like this? Help messages for query editor is a built-in feature in recent versions of Grafana. Unfortunately, help messages don't have access to the data so I couldn't build dynamic help messages this way.

![CleanShot 2021-02-18 at 11 47 35@2x](https://user-images.githubusercontent.com/8396880/108346038-3a9dd500-71df-11eb-97d0-a9bcfc0bcf13.png)

Other options I can think of is auto-completion in the query field, based on the data returned (the API for this is unfortunately pretty complicated though), and a more graphical editor.

You could build something like the Graphite editor where you drill down into each JSON object using dropdowns.

<img width="604" alt="CleanShot 2021-02-18 at 11 54 01@2x" src="https://user-images.githubusercontent.com/8396880/108346757-05de4d80-71e0-11eb-9fe2-42866e3dd7bc.png">

**Comment by marcusolsson** [comment]
Is this feature request still valid now that the plugin now has auto-completion for JSONPath expressions?

**Comment by smarkm** [comment]
> Is this feature request still valid now that the plugin now has auto-completion for JSONPath expressions?

Yes, `auto-completion` is good for help now
