### ISSUE TITLE
The origin URL can be expose ?

### ISSUE THREAD

**Issue by smarkm** [marcusolsson/grafana-json-datasource#75]
I am trying to get the origin URL in one panel with this code `var ds = config.datasources["JSON API"];`, is it possible? or any concern if expose it there?

**Comment by marcusolsson** [comment]
Which panel are you using? That looks like a custom API for that panel so I can't say whether it's possible or not.

**Comment by smarkm** [comment]
Sorry @marcusolsson , actually what I want to do is get HTTP header value in code like this
![image](https://user-images.githubusercontent.com/5517120/112167049-22c8cf00-8c2b-11eb-9d62-d995139b262b.png)

**Comment by marcusolsson** [comment]
What do you mean by "in code"? Are you considering contributing to the project? Where are you writing this code?

Values for custom HTTP headers are encrypted on the backend so depending on where you use it, it may not be available to you.

**Comment by smarkm** [comment]
Sorry, I am develop a local panel plugin, `in code` means in my panel code  it will load data rely on configured JSON datasource, the code will like this, I want to check the header configured before execute fetch
![image](https://user-images.githubusercontent.com/5517120/112236371-4451a700-8c7b-11eb-902f-4204dd59294e.png)

**Comment by marcusolsson** [comment]
I can't see the type of `ds`, but assuming it's [DataSourceApi](https://grafana.com/docs/grafana/latest/packages_api/data/datasourceapi/), I'm not sure you can access it unless the data source explicitly exposes it. 

I'm going to close this, as it doesn't really have anything to do with this data source specifically. If you have general questions on plugin development, I recommend that you ask them on https://community.grafana.com.
