### ISSUE TITLE
URL appended with datasource path

### ISSUE THREAD

**Issue by kumar-m-kiran** [marcusolsson/grafana-json-datasource#78]
**Description**
I am trying to run a `POST` method call to the `url` end-point (a hosted server). However, the plugin appends `api/datasource/proxy/2`.

**Bug**
My expectation is that the prefix should not be added. What is configured should be used for the `url` end-point.

I have attached the screen shot to provide a more clearer info.
<img width="1438" alt="Screen Shot 2021-03-11 at 12 32 43 PM" src="https://user-images.githubusercontent.com/13248602/110748823-491f5f80-8266-11eb-9516-2a9c61382dce.png">

Is this a bug or a expected behavior?

**Comment by kumar-m-kiran** [comment]
It was an incorrect set-up at my end. Closing the issue.

**Comment by zgldh** [comment]
How did you fix this?
