### ISSUE TITLE
Please remove the time type length checking in detectFieldType 

### ISSUE THREAD

**Issue by jiulian** [marcusolsson/grafana-json-datasource#82]
https://github.com/marcusolsson/grafana-json-datasource/blob/4352df6d0a48dcbf14597d575a7cbc9f79a2a590/src/datasource.ts#L202-L209

This checking will cause the value to wrongly display to time value, it is quite annoying.
For example 2257757352, we want to display this length of the value in our project, but it displayed '2041-07-18 18:49:12'.

**Comment by marcusolsson** [comment]
Now that we have support for setting the type explicitly, I think it's reasonable to not automatically detect Unix epochs. In the meantime, you should be able to fix this by setting the type as Number.
