### ISSUE TITLE
Error on adding datasource to Grafana v7.2.2

### ISSUE THREAD

**Issue by robotparty** [marcusolsson/grafana-json-datasource#84]
During the 'add a datasource' step, after selecting this plugin, the next screen shows the following: 

```
An unexpected error happened
DetailsError: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    in Unknown
    in div
    in t
    in form
    in div
    in div
    in t
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in x
    in ConnectWithCleanUp(Connect(t))
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l
```

**Comment by marcusolsson** [comment]
Hi, the error you're getting is a generic error for when the plugin requires features from more recent versions of Grafana. This currently only supports Grafana >=7.3.0.

**Comment by amychod** [comment]
> Hi, the error you're getting is a generic error for when the plugin requires features from more recent versions of Grafana. This currently only supports Grafana >=7.3.0.

To clarify this plugin needs Grafana >=7.3.0?

**Comment by robotparty** [comment]
Ok thanks! sorry for the delay in responding, story got backlogged.
