### ISSUE TITLE
Params in "Params" is not updating when variables changes.

### ISSUE THREAD

**Issue by ZuperZee** [marcusolsson/grafana-json-datasource#85]
When using variables in the "Params" option and change the variable, the query doesn't change.

https://user-images.githubusercontent.com/39485579/112290812-df547c00-8c8f-11eb-9c18-00eb63027d2d.mp4

### Param in "Path" panel

![image](https://user-images.githubusercontent.com/39485579/112291840-cb5d4a00-8c90-11eb-88f7-bff2ed4d1b44.png)
![image](https://user-images.githubusercontent.com/39485579/112292141-137c6c80-8c91-11eb-94ea-f8269ac91703.png)

### Param in "Params" panel

![image](https://user-images.githubusercontent.com/39485579/112292022-f9428e80-8c90-11eb-82d8-baa7f0c5f712.png)
![image](https://user-images.githubusercontent.com/39485579/112291877-d44e1b80-8c90-11eb-8168-580978daec3c.png)

### Some additional notes

There is no query string added to the datasource setup.
Docker and the API is in a docker container.
![image](https://user-images.githubusercontent.com/39485579/112290854-e9767a80-8c8f-11eb-85ad-9c7b9b230e67.png)

Grafana version: 7.4.3
Plugin version: 1.0.1

**Comment by marcusolsson** [comment]
This is likely due to the cache. I can see that you've configured the cache to 5 minutes. Currently, the cache key is set to the URL + the path, but I'm considering adding the params to the cache key as well. It should work for you if you set the cache time to 0s.

**Comment by ZuperZee** [comment]
That would be great.

P.S.
It does update when the cache is set to 0s.

**Comment by libeilin** [comment]
#/ #


Hi, I have encountered two issues here. One is that modifying the cache time does not take effect, and the other is that when changing the variable value, Grafana does not reissue the query request.
