### ISSUE TITLE
Data links relying on values don't update after sorting

### ISSUE THREAD

**Issue by jlyons6100** [marcusolsson/grafana-json-datasource#90]
I'm using some of the values returned by my queries to create datalinks. It seems that sorting the table doesn't update the datalink with the current value in the correct position. I'm not sure I described this with enough detail so I attached some images. In the first picture, hovering over thing 1 uses the correct value for the data link. However, in the second, Thing 1 is used again even when hovering over Thing 2 after sorting.

<img width="922" alt="Screen Shot 2021-04-07 at 12 21 13 PM" src="https://user-images.githubusercontent.com/2278962/113922304-ff119700-979b-11eb-92a3-530018d56d75.png">
<img width="924" alt="Screen Shot 2021-04-07 at 12 21 29 PM" src="https://user-images.githubusercontent.com/2278962/113922297-fd47d380-979b-11eb-91eb-29f66ed6d6f6.png">

**Comment by marcusolsson** [comment]
Closing this as it seems unrelated to the JSON API plugin. Please let me if I got it wrong and we'll reopen it.
