### ISSUE TITLE
Unable to change field parameters when using plugin as Variable provider

### ISSUE THREAD

**Issue by henley-regatta** [marcusolsson/grafana-json-datasource#94]
I've got an _extremely_ simple datasource consisting of time:value pairs in JSON served as a simple file.
I've used your API to grab that data and, through a little trial and error worked out how to get the key/values out. Since the timestamp is effectively the key I'm using `$..*~` to get that (I don't care about the value associated for the purposes of this variable's use). However, Javascript is interpreting the string as a timestamp and I don't want that.
![image](https://user-images.githubusercontent.com/42374576/114548270-74c3aa00-9c57-11eb-862f-3d2a364e3af4.png)
![image](https://user-images.githubusercontent.com/42374576/114548322-83aa5c80-9c57-11eb-8785-2e3233ca3f2f.png)
I _can_ select "String" manually from the **Type** selector:
![image](https://user-images.githubusercontent.com/42374576/114548455-b05e7400-9c57-11eb-96d6-3411bc161fa4.png)
...but it makes no difference. Using the "Update" button, or using "Save Dashboard". doesn't result in a data change: coming back in I find I'm back to looking at "Type: Auto":
![image](https://user-images.githubusercontent.com/42374576/114548672-fca9b400-9c57-11eb-9e1b-91bfdd76aae3.png)
then re-examining: 
![image](https://user-images.githubusercontent.com/42374576/114548719-0b906680-9c58-11eb-843d-f3b2122a0652.png)
...it's back to "Auto".

This is with Plugin v1.0.1 on Grafana 7.5.3.

Thanks for any help.

**Comment by marcusolsson** [comment]
I've removed auto detection of timestamps as Time fields with [this](https://github.com/marcusolsson/grafana-json-datasource/issues/82), though it's yet to be released.

I can reproduce the issue with the type not being saved however. Will look into it! Thanks for reporting!

**Comment by marcusolsson** [comment]
I've just published [v1.1.0](https://grafana.com/grafana/plugins/marcusolsson-json-datasource/) to the marketplace. While I haven't worked on this specifically. I've fixed a couple of related issues. Would you mind letting me know if this issue is still there in 1.1.0?

**Comment by henley-regatta** [comment]
> I've just published [v1.1.0](https://grafana.com/grafana/plugins/marcusolsson-json-datasource/) to the marketplace. While I haven't worked on this specifically. I've fixed a couple of related issues. Would you mind letting me know if this issue is still there in 1.1.0?

Hey @marcusolsson great work, this fixed it brilliantly! Getting exactly the output I need now I can force formatting on variables and I appreciate the "alias" feature too!
