### ISSUE TITLE
$__unixEpochFrom() and $__unixEpochTo() don't work in variable queries

### ISSUE THREAD

**Issue by KensingtonTech** [marcusolsson/grafana-json-datasource#98]
$__unixEpochFrom() and $__unixEpochTo() don't appear to resolve when being used as query params in a variable query.

![image](https://user-images.githubusercontent.com/15734900/115616552-52b4d200-a2be-11eb-8c6d-ef053d69b26b.png)

On a simple node express app with this route:

```app.get('/test', (req, res, next) => {
  console.log('query:', req.query);
  res.status(200).send('ok');
}
```

Yields:

```query: {
  time1: [ '$__unixEpochFrom()', '$__unixEpochFrom()' ],
  time2: [ '$__unixEpochTo()', '$__unixEpochTo()' ]
}
```

They're coming through as string literals.  Hopefully I'm not just doing something wrong!

**Comment by KensingtonTech** [comment]
Found the problem:

datasource.ts:
Problem:
```async metricFindQuery?(query: JsonApiQuery): Promise<MetricFindValue[]> {
  const frames = await this.doRequest(query);
```

Solution:
```async metricFindQuery?(query: JsonApiQuery, options: any): Promise<MetricFindValue[]> {
  const frames = await this.doRequest(query, options.range);
```

Will send a PR tomorrow.

**Comment by marcusolsson** [comment]
Fixed in v.1.2.0
